apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "srg.fullname" . }}-config
  labels:
    {{- include "srg.labels" . | nindent 4 }}
data:
  SRG_ENV: {{ .Values.env.env | quote }}
  SRG_DEFAULT_MODEL: {{ .Values.env.defaultModel | quote }}
  SRG_MODEL_CATALOG: {{ .Values.env.modelCatalog | quote }}
  SRG_PROVIDER_NAME: {{ .Values.env.providerName | quote }}
  SRG_OPA_MODE: {{ .Values.env.opaMode | quote }}
  SRG_REDACTION_ENABLED: {{ .Values.env.redactionEnabled | quote }}
  SRG_RAG_ENABLED: {{ .Values.env.ragEnabled | quote }}
  SRG_RAG_ALLOWED_CONNECTORS: {{ .Values.env.ragAllowedConnectors | quote }}
  SRG_RAG_SHAREPOINT_BASE_URL: {{ .Values.env.ragSharepointBaseUrl | quote }}
  SRG_RAG_SHAREPOINT_SITE_ID: {{ .Values.env.ragSharepointSiteId | quote }}
  SRG_RAG_SHAREPOINT_DRIVE_ID: {{ .Values.env.ragSharepointDriveId | quote }}
  SRG_RAG_SHAREPOINT_AUTH_MODE: {{ .Values.env.ragSharepointAuthMode | quote }}
  SRG_RAG_SHAREPOINT_BEARER_TOKEN: {{ .Values.env.ragSharepointBearerToken | quote }}
  SRG_RAG_SHAREPOINT_MANAGED_IDENTITY_ENDPOINT: {{ .Values.env.ragSharepointManagedIdentityEndpoint | quote }}
  SRG_RAG_SHAREPOINT_MANAGED_IDENTITY_RESOURCE: {{ .Values.env.ragSharepointManagedIdentityResource | quote }}
  SRG_RAG_SHAREPOINT_MANAGED_IDENTITY_API_VERSION: {{ .Values.env.ragSharepointManagedIdentityApiVersion | quote }}
  SRG_RAG_SHAREPOINT_MANAGED_IDENTITY_CLIENT_ID: {{ .Values.env.ragSharepointManagedIdentityClientId | quote }}
  SRG_RAG_SHAREPOINT_MANAGED_IDENTITY_TIMEOUT_S: {{ .Values.env.ragSharepointManagedIdentityTimeoutS | quote }}
  SRG_RAG_SHAREPOINT_ALLOWED_PATH_PREFIXES: {{ .Values.env.ragSharepointAllowedPathPrefixes | quote }}
  SRG_RAG_SHAREPOINT_CACHE_TTL_SECONDS: {{ .Values.env.ragSharepointCacheTtlSeconds | quote }}
  SRG_LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  SRG_AUDIT_LOG_PATH: {{ .Values.env.auditLogPath | quote }}
  SRG_METRICS_ENABLED: {{ .Values.env.metricsEnabled | quote }}
  SRG_PROVIDER_FALLBACK_ENABLED: {{ .Values.env.providerFallbackEnabled | quote }}
  SRG_BUDGET_ENABLED: {{ .Values.env.budgetEnabled | quote }}
  SRG_BUDGET_DEFAULT_CEILING: {{ .Values.env.budgetDefaultCeiling | quote }}
  SRG_BUDGET_WINDOW_SECONDS: {{ .Values.env.budgetWindowSeconds | quote }}
  SRG_BUDGET_TENANT_CEILINGS: {{ .Values.env.budgetTenantCeilings | quote }}
  SRG_BUDGET_BACKEND: {{ .Values.env.budgetBackend | quote }}
  SRG_BUDGET_REDIS_URL: {{ .Values.env.budgetRedisUrl | quote }}
  SRG_BUDGET_REDIS_PREFIX: {{ .Values.env.budgetRedisPrefix | quote }}
  SRG_BUDGET_REDIS_TTL_SECONDS: {{ .Values.env.budgetRedisTtlSeconds | quote }}
  SRG_WEBHOOK_ENABLED: {{ .Values.env.webhookEnabled | quote }}
  SRG_WEBHOOK_ENDPOINTS: {{ .Values.env.webhookEndpoints | quote }}
  SRG_WEBHOOK_TIMEOUT_S: {{ .Values.env.webhookTimeoutS | quote }}
  SRG_WEBHOOK_MAX_RETRIES: {{ .Values.env.webhookMaxRetries | quote }}
  SRG_WEBHOOK_BACKOFF_BASE_S: {{ .Values.env.webhookBackoffBaseS | quote }}
  SRG_WEBHOOK_BACKOFF_MAX_S: {{ .Values.env.webhookBackoffMaxS | quote }}
  SRG_WEBHOOK_DEAD_LETTER_BACKEND: {{ .Values.env.webhookDeadLetterBackend | quote }}
  SRG_WEBHOOK_DEAD_LETTER_PATH: {{ .Values.env.webhookDeadLetterPath | quote }}
  SRG_WEBHOOK_DEAD_LETTER_RETENTION_DAYS: {{ .Values.env.webhookDeadLetterRetentionDays | quote }}
  SRG_TRACING_ENABLED: {{ .Values.env.tracingEnabled | quote }}
  SRG_TRACING_MAX_TRACES: {{ .Values.env.tracingMaxTraces | quote }}
  SRG_TRACING_OTLP_ENABLED: {{ .Values.env.tracingOtlpEnabled | quote }}
  SRG_TRACING_OTLP_ENDPOINT: {{ .Values.env.tracingOtlpEndpoint | quote }}
  SRG_TRACING_OTLP_TIMEOUT_S: {{ .Values.env.tracingOtlpTimeoutS | quote }}
  SRG_TRACING_OTLP_HEADERS: {{ .Values.env.tracingOtlpHeaders | quote }}
  SRG_TRACING_SERVICE_NAME: {{ .Values.env.tracingServiceName | quote }}
