{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "srg.fullname" . }}
  labels:
    {{- include "srg.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "srg.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.allowIngressFromSameNamespace }}
    - from:
        - podSelector: {}
    {{- else }}
    - []
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.allowDNS }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- range .Values.networkPolicy.extraEgressCIDRs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
