{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "srg.fullname" . }}
  labels:
    {{- include "srg.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "srg.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "srg.fullname" . }}
{{- end }}
