apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srg.fullname" . }}-auth
  labels:
    {{- include "srg.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ join "," .Values.env.apiKeys | quote }}
